// FILE: src/sw.ts
/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute, matchPrecache } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { ExpirationPlugin } from "workbox-expiration";
import { clientsClaim } from "workbox-core";

declare let self: ServiceWorkerGlobalScope;

// --- 1. Lifecycle & cleanup ---
// ✅ FIX: Explicitly ignore promise
void self.skipWaiting();
clientsClaim(); 
cleanupOutdatedCaches();

// --- 2. Precache (Generated by Vite) ---
precacheAndRoute(self.__WB_MANIFEST);

// --- 3. Runtime Caching for Dev/Dynamic Assets ---
registerRoute(
  ({ request }) => 
    request.destination === "script" || 
    request.destination === "style" || 
    request.destination === "worker",
  new StaleWhileRevalidate({
    cacheName: "assets-runtime",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 24 * 60 * 60 }),
    ]
  })
);

// --- 4. Navigation Fallback (Offline Page Reloads) ---
// ✅ FIX: Rename params to _ since it is unused
const navigationHandler = async (_: { request: Request; url: URL }) => {
  try {
    const precached = await matchPrecache("/index.html");
    if (precached) return precached;

    const runtimeCache = await caches.open("pages");
    const cachedResponse = await runtimeCache.match("/index.html");
    if (cachedResponse) return cachedResponse;

    const networkResponse = await fetch("/index.html");
    if (networkResponse.ok) {
        await runtimeCache.put("/index.html", networkResponse.clone());
    }
    return networkResponse;
  } catch (error) {
    console.error("[SW] Navigation handler failed:", error);
    return Response.error(); 
  }
};

const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [
    /^\/api\//, 
    /^\/ws\//,  
  ],
});

registerRoute(navigationRoute);

// --- 5. Asset Caching (Images) ---
const mediaStrategy = new CacheFirst({
  cacheName: "media-cache",
  matchOptions: {
    // ✅ FIX: Relax matching to ensure opaque responses found by URL are returned
    ignoreVary: true,
    ignoreSearch: true,
  },
  plugins: [
    new CacheableResponsePlugin({ statuses: [0, 200] }),
    new ExpirationPlugin({
      maxEntries: 500,
      maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
    }),
  ],
});

registerRoute(
  ({ url }) => {
    const isMedia = url.hostname.includes("r2.dev") || url.hostname.includes("cloudflarestorage.com");
    return isMedia;
  },
  mediaStrategy
);

// --- 6. Skip Waiting Listener ---
self.addEventListener("message", (event: ExtendableMessageEvent) => {
  if (event.data && (event.data as Record<string, unknown>).type === "SKIP_WAITING") {
    void self.skipWaiting();
  }
});
